Vagrant.configure("2") do |o|
  o.vm.box = "ubuntu/trusty64"
  
  o.vm.network :private_network, ip: "192.168.44.44"

  o.vm.provision :shell, :path => "./provision-trusty64.sh"

  o.vm.synced_folder "../docroot/", "/var/www/docroot", create:true, owner: "vagrant", group: "www-data"
end
